# Preparation Course {#w0-preparation}

In this course we will be using R and RStudio. We ask you to install and/or update these programs *before* the start of the course, so that we do not loose time once the course starts. In this chapter, we cover the course requirements and some tips on how you should change your RStudio settings. 

```{r}
#| echo: false
#| include: false

library("rversions")
library("lubridate")

rv <- rversions::r_release()
rv

rve <- strsplit(as.character(base::getRversion()), "\\.")[[1]]

rversion_minimal <- function(version_string){
  version_int <- as.integer(strsplit(version_string, "\\.")[[1]])
  paste(version_int[1], ifelse(version_int[2] == 0, version_int[2], version_int[2]-1), 0,sep = ".")
}

heute <- paste(month(Sys.Date(), TRUE, FALSE, "C"), year(Sys.Date()), sep = ", ")
```

## Install R

If you haven't installed R yet, do so now by getting the newest version from [CRAN](https://cran.r-project.org/). 



## Install RStudio

[RStudio](https://posit.co/download/rstudio-desktop/) is the IDE (integrated development environment) we use in our course to interact with R. Download and install it on your computer.


## Configure RStudio{#configure-rstudio}

Now we will set some RStudio Global options. But first, **close all instances of RStudio and restart it (!!!)**. Then go to Tools > Global options. 

- **R General**
  - Deactivate the option "Restore .RData into workspace at startup"
  - Set "Save workspace to .RData on exit " to "Never"
- **Code**
  - Activate the option "Use native pipe operator, |> (requires R 4.1+)"
- **R Markdown**
  - Deactivate the option "Show output inline for all R Markdown documents"


Click on "Ok" to apply the change and close the options menu.


### Folder structure for this course {#folder-structure}

By this point, you probably have created a folder for this course somewhere on your computer. In our example, we assume this folder is located here: `C:/Users/yourname/semester2/Module_DAMO` (mentally replace this with your actual path). Before we dive into the exercises, take a minute to think about how you are going to structure your files in this folder. This course will take place over several weeks, and in each week you will receive or produce various files. We recommend creating a separate folder for each week, and one folder for the case studies, like so:

```
Course Folder (C:\\Users\\yourname\\semester2\\Module_DAMO)
 ¦--week_1                                                
 ¦--week_2                                                
 ¦--week_3                                                
 |--...                                                
 °--case_studies 
```

For the R-exercises we recommend that you create a new RStudio Project each week in subdirectory of the appropriate week. For example, this week your folder structure could look like this: 

```
Folder Week 1 (C:\\Users\\yourname\\semester2\\Module_DAMO\\week_1)
 ¦--slides.pdf                                                  
 ¦--my_notes.docx                                               
 ¦--seminar_screenshot.jpg                                      
 °---damo-week1-rexercise                                             
     ¦--damo-week1-rexercise.Rproj                                   
     ¦--test.csv                                      
     °--my_solution.qmd   
```

Note: 

- the RStudio Project is located in a subfolder of `C:/Users/yourname/semester1/Module_DAMO/week_1` and named `damo-week1-rexercise`.
- `damo-week1-rexercise` is the project's *directory name* and the *project name*
- we realize that `damo` and the week number is redundant, there is a reason[^redundancy] for this
- this means each week is a fresh start (which has pros and cons)

[^redundancy]: You will see the project names of all your RStudio Projects listed in RStudio. Having the week number in the project name keeps you from getting confused on which project you are working on.

### Create an RStudio *project* for the first week

Create a new *RStudio Project* (File > New Project > New Directory > New Project). 

1. Click on "Browse" and switch to *your equivalent* of the folder `C:/Users/yourname/semester1/Module_DAMO/week_1` (the project we are about to initiate will be be created in a subdirectory of this folder). Click on "open" to confirm the selection
2. In the field "Directory name", type `damo-week1-rexercise`. This will be the name of your RStudio project and it's parent directory.
3. Click on "Create Project"

You are all set! You can start working on the tasks of exercise 1.